# Automation / CI Status
- name: "ci: failing"
  color: "d73a4a"
  description: "CI failed on default checks"
- name: "ci: flaky"
  color: "fbca04"
  description: "Intermittent CI failures observed"
- name: "ci: blocked"
  color: "6a737d"
  description: "CI cannot run due to missing secrets or env"
- name: "ci: passing"
  color: "0e8a16"
  description: "All required checks passing"
- name: "automation: dependabot"
  color: "c5def5"
  description: "Automated PR opened by Dependabot"

# Issue Types
- name: "type: bug"
  color: "d73a4a"
  description: "Defect or regression"
- name: "type: feature"
  color: "0e8a16"
  description: "New user-facing capability"
- name: "type: enhancement"
  color: "1d76db"
  description: "Improvement to existing behavior"
- name: "type: chore"
  color: "cfd3d7"
  description: "Maintenance or refactor"
- name: "type: docs"
  color: "0075ca"
  description: "Documentation-only change"
- name: "type: dependencies"
  color: "0366d6"
  description: "Dependency updates or lockfile changes"
- name: "type: refactor"
  color: "a2eeef"
  description: "Code structure changes without behavior change"
- name: "type: performance"
  color: "f9d0c4"
  description: "Performance or cost improvements"
- name: "type: question"
  color: "d876e3"
  description: "Clarification or discussion"
- name: "type: security"
  color: "b60205"
  description: "Security-related issue"

# PR Scope / Areas
- name: "scope: agent-core"
  color: "0e8a9b"
  description: "Agent lifecycle, state, prompts, policies"
- name: "scope: orchestration"
  color: "0e8a9b"
  description: "Planning, routing, scheduling, coordination"
- name: "scope: tools"
  color: "0e8a9b"
  description: "Tool registry, execution, adapters"
- name: "scope: memory"
  color: "0e8a9b"
  description: "Memory store, embeddings, retrieval"
- name: "scope: ui"
  color: "0e8a9b"
  description: "Desktop UI and interaction surfaces"
- name: "scope: api"
  color: "0e8a9b"
  description: "Internal or external APIs"
- name: "scope: integrations"
  color: "0e8a9b"
  description: "External services and providers"
- name: "scope: infra"
  color: "0e8a9b"
  description: "Build, CI, deployment, scripts"
- name: "scope: docs"
  color: "0e8a9b"
  description: "Docs specific to a PR’s area"
- name: "scope: tests"
  color: "0e8a9b"
  description: "Test-only changes"
- name: "scope: dependencies"
  color: "0e8a9b"
  description: "Package updates and lockfiles"

# Priority / Severity
- name: "priority: p0"
  color: "b60205"
  description: "Must fix immediately"
- name: "priority: p1"
  color: "d93f0b"
  description: "High priority, near-term"
- name: "priority: p2"
  color: "fbca04"
  description: "Normal priority"
- name: "priority: p3"
  color: "0e8a16"
  description: "Low priority"
- name: "severity: s0"
  color: "8b0000"
  description: "System-wide or data-loss impact"
- name: "severity: s1"
  color: "d93f0b"
  description: "Major user impact"
- name: "severity: s2"
  color: "fbca04"
  description: "Minor or localized impact"

# Status
- name: "status: needs-triage"
  color: "ededed"
  description: "New, unreviewed"
- name: "status: needs-info"
  color: "fbca04"
  description: "Blocked on reporter details"
- name: "status: accepted"
  color: "1d76db"
  description: "Approved to work on"
- name: "status: in-progress"
  color: "0052cc"
  description: "Actively being worked"
- name: "status: blocked"
  color: "d93f0b"
  description: "External dependency or hard block"
- name: "status: on-hold"
  color: "bdbdbd"
  description: "Paused pending decision or timing"
- name: "status: ready-for-review"
  color: "5319e7"
  description: "Implementation done; needs review"
- name: "status: done"
  color: "0e8a16"
  description: "Completed and verified"
- name: "status: duplicate"
  color: "cccccc"
  description: "Duplicate of an existing issue"
- name: "status: wontfix"
  color: "666666"
  description: "Closed without planned changes"
