import {
    accountSnapshotStore,
    conversationStore,
    diffStore,
    marketplaceStore,
    messageStore,
    mcpStore,
    modeStore,
    permissionStore,
    providerAuthFlowStore,
    rulesetStore,
    runStore,
    runUsageStore,
    runtimeEventStore,
    secretReferenceStore,
    sessionStore,
    skillfileStore,
    tagStore,
    threadStore,
    toolStore,
} from '@/app/backend/persistence/stores';
import type { RuntimeSnapshotV1 } from '@/app/backend/persistence/types';
import { providerManagementService } from '@/app/backend/providers/service';

export interface RuntimeSnapshotService {
    getSnapshot(profileId: string): Promise<RuntimeSnapshotV1>;
}

class RuntimeSnapshotServiceImpl implements RuntimeSnapshotService {
    async getSnapshot(profileId: string): Promise<RuntimeSnapshotV1> {
        const [
            sessions,
            runs,
            messages,
            messageParts,
            runUsage,
            providerUsageSummaries,
            permissions,
            providers,
            providerModels,
            providerAuthStates,
            providerAuthFlows,
            providerDiscoverySnapshots,
            tools,
            mcpServers,
            defaults,
            lastSequence,
            conversations,
            threads,
            tags,
            threadTags,
            diffs,
            modeDefinitions,
            rulesets,
            skillfiles,
            marketplacePackages,
            kiloAccountContext,
            secretReferences,
        ] = await Promise.all([
            sessionStore.list(profileId),
            runStore.listByProfile(profileId),
            messageStore.listMessagesByProfile(profileId),
            messageStore.listPartsByProfile(profileId),
            runUsageStore.listByProfile(profileId),
            runUsageStore.summarizeByProfile(profileId),
            permissionStore.listAll(),
            providerManagementService.listProviders(profileId),
            providerManagementService.listModelsByProfile(profileId),
            providerManagementService.listAuthStates(profileId),
            providerAuthFlowStore.listByProfile(profileId),
            providerManagementService.listDiscoverySnapshots(profileId),
            toolStore.list(),
            mcpStore.listServers(),
            providerManagementService.getDefaults(profileId),
            runtimeEventStore.getLastSequence(),
            conversationStore.listBuckets(profileId),
            threadStore.list({
                profileId,
                sort: 'latest',
            }),
            tagStore.listByProfile(profileId),
            tagStore.listThreadTagsByProfile(profileId),
            diffStore.listByProfile(profileId),
            modeStore.listByProfile(profileId),
            rulesetStore.listByProfile(profileId),
            skillfileStore.listByProfile(profileId),
            marketplaceStore.listPackages(),
            accountSnapshotStore.getByProfile(profileId),
            secretReferenceStore.listByProfile(profileId),
        ]);

        return {
            generatedAt: new Date().toISOString(),
            lastSequence,
            sessions,
            runs,
            messages,
            messageParts,
            runUsage,
            providerUsageSummaries,
            permissions,
            providers,
            providerModels,
            providerAuthStates,
            providerAuthFlows,
            providerDiscoverySnapshots,
            tools,
            mcpServers,
            conversations,
            threads,
            tags,
            threadTags,
            diffs,
            modeDefinitions,
            rulesets,
            skillfiles,
            marketplacePackages,
            kiloAccountContext,
            secretReferences,
            defaults,
        };
    }
}

export const runtimeSnapshotService: RuntimeSnapshotService = new RuntimeSnapshotServiceImpl();
