// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.

export interface RuntimeSqlMigration {
    name: string;
    sql: string;
}

export const runtimeSqlMigrations: RuntimeSqlMigration[] = [
    {
        name: '001_init.sql',
        sql: `
CREATE TABLE IF NOT EXISTS schema_migrations (
    name TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    supports_byok INTEGER NOT NULL CHECK (supports_byok IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS provider_models (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_provider_models_provider_id ON provider_models(provider_id);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    kind TEXT NOT NULL,
    run_status TEXT NOT NULL,
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_runs_session_id_created_at ON runs(session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    policy TEXT NOT NULL,
    resource TEXT NOT NULL,
    decision TEXT NOT NULL,
    rationale TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_permissions_decision_created_at ON permissions(decision, created_at);

CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_settings_profile_key ON settings(profile_id, key);

CREATE TABLE IF NOT EXISTS runtime_events (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_runtime_events_sequence ON runtime_events(sequence);

CREATE TABLE IF NOT EXISTS tools_catalog (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL,
    permission_policy TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mcp_servers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    auth_mode TEXT NOT NULL,
    connection_state TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
`,
    },
    {
        name: '002_core_runtime.sql',
        sql: `
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS threads (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_threads_conversation_id_updated_at
    ON threads(conversation_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS tags (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS thread_tags (
    thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (thread_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_thread_tags_tag_id ON thread_tags(tag_id);

CREATE TABLE IF NOT EXISTS diffs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_diffs_session_id_created_at
    ON diffs(session_id, created_at DESC);
`,
    },
    {
        name: '003_p1c_runtime_foundation.sql',
        sql: `
ALTER TABLE sessions
    ADD COLUMN workspace_fingerprint TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_sessions_workspace_fingerprint
    ON sessions(workspace_fingerprint);

ALTER TABLE conversations
    ADD COLUMN workspace_fingerprint TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_workspace_fingerprint
    ON conversations(workspace_fingerprint);

INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
VALUES (
    'profile_local_default',
    'Local Default',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
SELECT
    CASE
        WHEN profile_id = '__global__' THEN 'profile_local_default'
        ELSE profile_id
    END AS id,
    'Migrated Profile',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM settings;

DROP INDEX IF EXISTS idx_settings_profile_key;

CREATE TABLE IF NOT EXISTS settings_v2 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO settings_v2 (id, profile_id, key, value_json, updated_at)
SELECT
    id,
    CASE
        WHEN profile_id = '__global__' THEN 'profile_local_default'
        ELSE profile_id
    END AS profile_id,
    key,
    value_json,
    updated_at
FROM settings;

DROP TABLE settings;

ALTER TABLE settings_v2
    RENAME TO settings;

CREATE UNIQUE INDEX IF NOT EXISTS idx_settings_profile_key
    ON settings(profile_id, key);
`,
    },
    {
        name: '004_p1d_kilo_parity.sql',
        sql: `
CREATE TABLE IF NOT EXISTS mode_definitions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    top_level_tab TEXT NOT NULL,
    mode_key TEXT NOT NULL,
    label TEXT NOT NULL,
    prompt_json TEXT NOT NULL,
    execution_policy_json TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mode_definitions_profile_tab_mode
    ON mode_definitions(profile_id, top_level_tab, mode_key);

CREATE TABLE IF NOT EXISTS rulesets (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workspace_fingerprint TEXT NULL,
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_rulesets_profile_scope_name
    ON rulesets(profile_id, ifnull(workspace_fingerprint, ''), name);

CREATE INDEX IF NOT EXISTS idx_rulesets_workspace_fingerprint
    ON rulesets(workspace_fingerprint);

CREATE TABLE IF NOT EXISTS skillfiles (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workspace_fingerprint TEXT NULL,
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_skillfiles_profile_scope_name
    ON skillfiles(profile_id, ifnull(workspace_fingerprint, ''), name);

CREATE INDEX IF NOT EXISTS idx_skillfiles_workspace_fingerprint
    ON skillfiles(workspace_fingerprint);

CREATE TABLE IF NOT EXISTS marketplace_packages (
    id TEXT PRIMARY KEY,
    package_kind TEXT NOT NULL,
    slug TEXT NOT NULL,
    version TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    pinned INTEGER NOT NULL CHECK (pinned IN (0, 1)),
    source_json TEXT NOT NULL,
    installed_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_marketplace_packages_kind_slug
    ON marketplace_packages(package_kind, slug);

CREATE TABLE IF NOT EXISTS marketplace_assets (
    package_id TEXT NOT NULL REFERENCES marketplace_packages(id) ON DELETE CASCADE,
    asset_kind TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (package_id, asset_kind, asset_id)
);

CREATE TABLE IF NOT EXISTS kilo_account_snapshots (
    profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    account_id TEXT NULL,
    display_name TEXT NOT NULL,
    email_masked TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    token_expires_at TEXT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kilo_org_snapshots (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL CHECK (is_active IN (0, 1)),
    entitlement_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kilo_org_snapshots_profile_org
    ON kilo_org_snapshots(profile_id, organization_id);

CREATE TABLE IF NOT EXISTS secret_references (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL,
    secret_key_ref TEXT NOT NULL,
    secret_kind TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_secret_references_profile_provider_kind
    ON secret_references(profile_id, provider_id, secret_kind);
`,
    },
    {
        name: '005_p2a_provider_auth_foundation.sql',
        sql: `
CREATE TABLE IF NOT EXISTS provider_auth_states (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    auth_method TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    account_id TEXT NULL,
    organization_id TEXT NULL,
    token_expires_at TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id)
);

CREATE TABLE IF NOT EXISTS provider_oauth_sessions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    flow_kind TEXT NOT NULL,
    state TEXT NOT NULL,
    code_verifier TEXT NOT NULL,
    redirect_uri TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    consumed_at TEXT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_oauth_sessions_profile_provider_state
    ON provider_oauth_sessions(profile_id, provider_id, state);

CREATE INDEX IF NOT EXISTS idx_provider_oauth_sessions_expires_at
    ON provider_oauth_sessions(expires_at);

CREATE TABLE IF NOT EXISTS provider_model_catalog (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    label TEXT NOT NULL,
    upstream_provider TEXT NULL,
    is_free INTEGER NOT NULL CHECK (is_free IN (0, 1)),
    supports_tools INTEGER NOT NULL CHECK (supports_tools IN (0, 1)),
    supports_reasoning INTEGER NOT NULL CHECK (supports_reasoning IN (0, 1)),
    context_length INTEGER NULL,
    pricing_json TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    source TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, model_id)
);

CREATE INDEX IF NOT EXISTS idx_provider_model_catalog_profile_provider_label
    ON provider_model_catalog(profile_id, provider_id, label);

CREATE TABLE IF NOT EXISTS provider_discovery_snapshots (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    etag TEXT NULL,
    payload_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, kind)
);

INSERT OR IGNORE INTO provider_model_catalog (
    profile_id,
    provider_id,
    model_id,
    label,
    upstream_provider,
    is_free,
    supports_tools,
    supports_reasoning,
    context_length,
    pricing_json,
    raw_json,
    source,
    updated_at
)
SELECT
    'profile_local_default',
    provider_id,
    id,
    label,
    provider_id,
    0,
    0,
    0,
    NULL,
    '{}',
    '{}',
    'seed',
    updated_at
FROM provider_models;

INSERT OR IGNORE INTO provider_auth_states (
    profile_id,
    provider_id,
    auth_method,
    auth_state,
    account_id,
    organization_id,
    token_expires_at,
    last_error_code,
    last_error_message,
    updated_at
)
SELECT
    'profile_local_default',
    id,
    'none',
    'logged_out',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM providers;
`,
    },
    {
        name: '006_p2b_auth_flow_rebuild.sql',
        sql: `
CREATE TABLE IF NOT EXISTS provider_auth_states_v2 (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    auth_method TEXT NOT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    auth_state TEXT NOT NULL CHECK (auth_state IN ('logged_out', 'pending', 'configured', 'authenticated', 'error', 'expired')),
    account_id TEXT NULL,
    organization_id TEXT NULL,
    token_expires_at TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id)
);

INSERT INTO provider_auth_states_v2 (
    profile_id,
    provider_id,
    auth_method,
    auth_state,
    account_id,
    organization_id,
    token_expires_at,
    last_error_code,
    last_error_message,
    updated_at
)
SELECT
    profile_id,
    provider_id,
    CASE
        WHEN auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device') THEN auth_method
        ELSE 'none'
    END AS auth_method,
    CASE
        WHEN auth_state IN ('logged_out', 'pending', 'configured', 'authenticated', 'error', 'expired') THEN auth_state
        ELSE 'logged_out'
    END AS auth_state,
    account_id,
    organization_id,
    token_expires_at,
    last_error_code,
    last_error_message,
    updated_at
FROM provider_auth_states;

DROP TABLE provider_auth_states;

ALTER TABLE provider_auth_states_v2
    RENAME TO provider_auth_states;

CREATE TABLE IF NOT EXISTS provider_auth_flows (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    flow_type TEXT NOT NULL CHECK (flow_type IN ('device_code', 'oauth_pkce', 'oauth_device')),
    auth_method TEXT NOT NULL CHECK (auth_method IN ('device_code', 'oauth_pkce', 'oauth_device')),
    nonce TEXT NULL,
    state TEXT NULL,
    code_verifier TEXT NULL,
    redirect_uri TEXT NULL,
    device_code TEXT NULL,
    user_code TEXT NULL,
    verification_uri TEXT NULL,
    poll_interval_seconds INTEGER NULL,
    expires_at TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'cancelled', 'expired', 'failed')),
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    consumed_at TEXT NULL
);

INSERT INTO provider_auth_flows (
    id,
    profile_id,
    provider_id,
    flow_type,
    auth_method,
    nonce,
    state,
    code_verifier,
    redirect_uri,
    device_code,
    user_code,
    verification_uri,
    poll_interval_seconds,
    expires_at,
    status,
    last_error_code,
    last_error_message,
    created_at,
    updated_at,
    consumed_at
)
SELECT
    id,
    profile_id,
    provider_id,
    CASE
        WHEN flow_kind = 'device_code' THEN 'device_code'
        ELSE 'oauth_pkce'
    END AS flow_type,
    CASE
        WHEN flow_kind = 'device_code' THEN 'device_code'
        ELSE 'oauth_pkce'
    END AS auth_method,
    NULL AS nonce,
    state,
    code_verifier,
    redirect_uri,
    NULL AS device_code,
    NULL AS user_code,
    NULL AS verification_uri,
    NULL AS poll_interval_seconds,
    expires_at,
    CASE
        WHEN consumed_at IS NULL THEN 'pending'
        ELSE 'completed'
    END AS status,
    NULL AS last_error_code,
    NULL AS last_error_message,
    created_at,
    created_at AS updated_at,
    consumed_at
FROM provider_oauth_sessions;

DROP TABLE provider_oauth_sessions;

CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_auth_flows_profile_provider_state
    ON provider_auth_flows(profile_id, provider_id, state);

CREATE INDEX IF NOT EXISTS idx_provider_auth_flows_expires_at
    ON provider_auth_flows(expires_at);

CREATE INDEX IF NOT EXISTS idx_provider_auth_flows_profile_provider_status
    ON provider_auth_flows(profile_id, provider_id, status);
`,
    },
    {
        name: '007_p2c_runtime_transport_and_usage.sql',
        sql: `
INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
VALUES (
    'profile_local_default',
    'Local Default',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS runs_v2 (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    provider_id TEXT NULL REFERENCES providers(id) ON DELETE SET NULL,
    model_id TEXT NULL,
    auth_method TEXT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    started_at TEXT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO runs_v2 (
    id,
    session_id,
    profile_id,
    prompt,
    status,
    provider_id,
    model_id,
    auth_method,
    started_at,
    completed_at,
    aborted_at,
    error_code,
    error_message,
    created_at,
    updated_at
)
SELECT
    id,
    session_id,
    'profile_local_default' AS profile_id,
    prompt,
    status,
    NULL AS provider_id,
    NULL AS model_id,
    NULL AS auth_method,
    created_at AS started_at,
    CASE WHEN status = 'completed' THEN updated_at ELSE NULL END AS completed_at,
    CASE WHEN status = 'aborted' THEN updated_at ELSE NULL END AS aborted_at,
    NULL AS error_code,
    NULL AS error_message,
    created_at,
    updated_at
FROM runs;

CREATE TABLE IF NOT EXISTS sessions_v2 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    scope TEXT NOT NULL,
    kind TEXT NOT NULL,
    workspace_fingerprint TEXT NULL,
    run_status TEXT NOT NULL,
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

INSERT INTO sessions_v2 (
    id,
    profile_id,
    scope,
    kind,
    workspace_fingerprint,
    run_status,
    pending_completion_run_id,
    created_at,
    updated_at
)
SELECT
    id,
    'profile_local_default' AS profile_id,
    scope,
    kind,
    workspace_fingerprint,
    run_status,
    pending_completion_run_id,
    created_at,
    updated_at
FROM sessions;

DROP TABLE sessions;
DROP TABLE runs;

ALTER TABLE sessions_v2 RENAME TO sessions;
ALTER TABLE runs_v2 RENAME TO runs;

CREATE INDEX IF NOT EXISTS idx_sessions_profile_updated_at
    ON sessions(profile_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_sessions_workspace_fingerprint
    ON sessions(workspace_fingerprint);

CREATE INDEX IF NOT EXISTS idx_runs_session_id_created_at
    ON runs(session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_runs_profile_created_at
    ON runs(profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_runs_profile_status
    ON runs(profile_id, status);

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_profile_session_created_at
    ON messages(profile_id, session_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_messages_run_created_at
    ON messages(run_id, created_at ASC);

CREATE TABLE IF NOT EXISTS message_parts (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    part_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_message_parts_message_sequence
    ON message_parts(message_id, sequence);

CREATE INDEX IF NOT EXISTS idx_message_parts_created_at
    ON message_parts(created_at);

CREATE TABLE IF NOT EXISTS run_usage (
    run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    input_tokens INTEGER NULL,
    output_tokens INTEGER NULL,
    cached_tokens INTEGER NULL,
    reasoning_tokens INTEGER NULL,
    total_tokens INTEGER NULL,
    latency_ms INTEGER NULL,
    cost_microunits INTEGER NULL,
    billed_via TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_run_usage_provider_recorded_at
    ON run_usage(provider_id, recorded_at DESC);
`,
    },
    {
        name: '008_p2_5_reasoning_and_cache_controls.sql',
        sql: `
ALTER TABLE runs ADD COLUMN reasoning_effort TEXT NULL
    CHECK (reasoning_effort IN ('none', 'minimal', 'low', 'medium', 'high', 'xhigh'));

ALTER TABLE runs ADD COLUMN reasoning_summary TEXT NULL
    CHECK (reasoning_summary IN ('auto', 'none'));

ALTER TABLE runs ADD COLUMN reasoning_include_encrypted INTEGER NULL
    CHECK (reasoning_include_encrypted IN (0, 1));

ALTER TABLE runs ADD COLUMN cache_strategy TEXT NULL
    CHECK (cache_strategy IN ('auto', 'manual'));

ALTER TABLE runs ADD COLUMN cache_key TEXT NULL;

ALTER TABLE runs ADD COLUMN cache_applied INTEGER NULL
    CHECK (cache_applied IN (0, 1));

ALTER TABLE runs ADD COLUMN cache_skip_reason TEXT NULL;

ALTER TABLE runs ADD COLUMN transport_openai_preference TEXT NULL
    CHECK (transport_openai_preference IN ('responses', 'chat', 'auto'));

ALTER TABLE runs ADD COLUMN transport_selected TEXT NULL
    CHECK (transport_selected IN ('responses', 'chat_completions'));

ALTER TABLE runs ADD COLUMN transport_degraded_reason TEXT NULL;
`,
    },
    {
        name: '009_p2_6_provider_capability_parity.sql',
        sql: `
ALTER TABLE provider_model_catalog ADD COLUMN supports_vision INTEGER NULL
    CHECK (supports_vision IN (0, 1));

ALTER TABLE provider_model_catalog ADD COLUMN supports_audio_input INTEGER NULL
    CHECK (supports_audio_input IN (0, 1));

ALTER TABLE provider_model_catalog ADD COLUMN supports_audio_output INTEGER NULL
    CHECK (supports_audio_output IN (0, 1));

ALTER TABLE provider_model_catalog ADD COLUMN input_modalities_json TEXT NULL;

ALTER TABLE provider_model_catalog ADD COLUMN output_modalities_json TEXT NULL;

ALTER TABLE provider_model_catalog ADD COLUMN prompt_family TEXT NULL;
`,
    },
    {
        name: '010_p3b_conversation_graph.sql',
        sql: `
INSERT OR IGNORE INTO profiles (id, name, created_at, updated_at)
VALUES (
    'profile_local_default',
    'Local Default',
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
);

PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS conversations_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    scope TEXT NOT NULL CHECK (scope IN ('detached', 'workspace')),
    workspace_fingerprint TEXT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_profile_scope_workspace
    ON conversations_v3(profile_id, scope, ifnull(workspace_fingerprint, ''));

CREATE INDEX IF NOT EXISTS idx_conversations_profile_scope_updated_at
    ON conversations_v3(profile_id, scope, updated_at DESC);

CREATE TABLE IF NOT EXISTS threads_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES conversations_v3(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_threads_profile_conversation_updated_at
    ON threads_v3(profile_id, conversation_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS tags_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_profile_label
    ON tags_v3(profile_id, label);

CREATE TABLE IF NOT EXISTS thread_tags_v3 (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES threads_v3(id) ON DELETE CASCADE,
    tag_id TEXT NOT NULL REFERENCES tags_v3(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, thread_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_thread_tags_profile_thread
    ON thread_tags_v3(profile_id, thread_id);

CREATE INDEX IF NOT EXISTS idx_thread_tags_profile_tag
    ON thread_tags_v3(profile_id, tag_id);

CREATE TABLE IF NOT EXISTS sessions_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES conversations_v3(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES threads_v3(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('local', 'worktree', 'cloud')),
    run_status TEXT NOT NULL CHECK (run_status IN ('idle', 'running', 'completed', 'aborted', 'error')),
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_profile_thread_updated_at
    ON sessions_v3(profile_id, thread_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_sessions_profile_conversation_updated_at
    ON sessions_v3(profile_id, conversation_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS diffs_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions_v3(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs_v3(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_diffs_profile_session_created_at
    ON diffs_v3(profile_id, session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS runs_v3 (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions_v3(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    provider_id TEXT NULL REFERENCES providers(id) ON DELETE SET NULL,
    model_id TEXT NULL,
    auth_method TEXT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    reasoning_effort TEXT NULL CHECK (reasoning_effort IN ('none', 'minimal', 'low', 'medium', 'high', 'xhigh')),
    reasoning_summary TEXT NULL CHECK (reasoning_summary IN ('auto', 'none')),
    reasoning_include_encrypted INTEGER NULL CHECK (reasoning_include_encrypted IN (0, 1)),
    cache_strategy TEXT NULL CHECK (cache_strategy IN ('auto', 'manual')),
    cache_key TEXT NULL,
    cache_applied INTEGER NULL CHECK (cache_applied IN (0, 1)),
    cache_skip_reason TEXT NULL,
    transport_openai_preference TEXT NULL CHECK (transport_openai_preference IN ('responses', 'chat', 'auto')),
    transport_selected TEXT NULL CHECK (transport_selected IN ('responses', 'chat_completions')),
    transport_degraded_reason TEXT NULL,
    started_at TEXT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages_v3 (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions_v3(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL REFERENCES runs_v3(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS message_parts_v3 (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL REFERENCES messages_v3(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    part_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS run_usage_v3 (
    run_id TEXT PRIMARY KEY REFERENCES runs_v3(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    input_tokens INTEGER NULL,
    output_tokens INTEGER NULL,
    cached_tokens INTEGER NULL,
    reasoning_tokens INTEGER NULL,
    total_tokens INTEGER NULL,
    latency_ms INTEGER NULL,
    cost_microunits INTEGER NULL,
    billed_via TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

DROP TABLE IF EXISTS thread_tags;
DROP TABLE IF EXISTS diffs;
DROP TABLE IF EXISTS message_parts;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS run_usage;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS conversations;

ALTER TABLE conversations_v3 RENAME TO conversations;
ALTER TABLE threads_v3 RENAME TO threads;
ALTER TABLE tags_v3 RENAME TO tags;
ALTER TABLE thread_tags_v3 RENAME TO thread_tags;
ALTER TABLE sessions_v3 RENAME TO sessions;
ALTER TABLE diffs_v3 RENAME TO diffs;
ALTER TABLE runs_v3 RENAME TO runs;
ALTER TABLE messages_v3 RENAME TO messages;
ALTER TABLE message_parts_v3 RENAME TO message_parts;
ALTER TABLE run_usage_v3 RENAME TO run_usage;

CREATE INDEX IF NOT EXISTS idx_runs_session_id_created_at
    ON runs(session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_runs_profile_created_at
    ON runs(profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_runs_profile_status
    ON runs(profile_id, status);

CREATE INDEX IF NOT EXISTS idx_messages_profile_session_created_at
    ON messages(profile_id, session_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_messages_run_created_at
    ON messages(run_id, created_at ASC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_message_parts_message_sequence
    ON message_parts(message_id, sequence);

CREATE INDEX IF NOT EXISTS idx_message_parts_created_at
    ON message_parts(created_at);

CREATE INDEX IF NOT EXISTS idx_run_usage_provider_recorded_at
    ON run_usage(provider_id, recorded_at DESC);

PRAGMA foreign_keys = ON;
`,
    },
    {
        name: '011_p4_2_plan_orchestrator_and_permission_overrides.sql',
        sql: `
CREATE TABLE IF NOT EXISTS plan_records (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    top_level_tab TEXT NOT NULL CHECK (top_level_tab IN ('chat', 'agent', 'orchestrator')),
    mode_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('awaiting_answers', 'draft', 'approved', 'implementing', 'implemented', 'failed', 'cancelled')),
    source_prompt TEXT NOT NULL,
    summary_markdown TEXT NOT NULL,
    questions_json TEXT NOT NULL DEFAULT '[]',
    answers_json TEXT NOT NULL DEFAULT '{}',
    workspace_fingerprint TEXT NULL,
    implementation_run_id TEXT NULL,
    orchestrator_run_id TEXT NULL,
    approved_at TEXT NULL,
    implemented_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(implementation_run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_plan_records_profile_session
    ON plan_records(profile_id, session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS plan_items (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(plan_id) REFERENCES plan_records(id) ON DELETE CASCADE,
    FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_plan_items_plan_sequence
    ON plan_items(plan_id, sequence);

CREATE TABLE IF NOT EXISTS orchestrator_runs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'aborted', 'failed')),
    active_step_index INTEGER NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(plan_id) REFERENCES plan_records(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_runs_profile_session
    ON orchestrator_runs(profile_id, session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS orchestrator_steps (
    id TEXT PRIMARY KEY,
    orchestrator_run_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(orchestrator_run_id) REFERENCES orchestrator_runs(id) ON DELETE CASCADE,
    FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orchestrator_steps_run_sequence
    ON orchestrator_steps(orchestrator_run_id, sequence);

CREATE TABLE IF NOT EXISTS permission_policy_overrides (
    profile_id TEXT NOT NULL,
    scope_key TEXT NOT NULL,
    resource TEXT NOT NULL,
    policy TEXT NOT NULL CHECK (policy IN ('ask', 'allow', 'deny')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, scope_key, resource)
);

CREATE INDEX IF NOT EXISTS idx_permission_policy_overrides_scope
    ON permission_policy_overrides(profile_id, scope_key);
`,
    },
    {
        name: '012_p4_3_profile_lifecycle.sql',
        sql: `
ALTER TABLE profiles
    ADD COLUMN is_active INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1));

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_single_active
    ON profiles(is_active)
    WHERE is_active = 1;

UPDATE profiles
SET is_active = 0;

UPDATE profiles
SET is_active = 1
WHERE id = 'profile_local_default';

UPDATE profiles
SET is_active = 1
WHERE is_active = 0
  AND id = (
      SELECT id
      FROM profiles
      ORDER BY created_at ASC, id ASC
      LIMIT 1
  );
`,
    },
    {
        name: '013_p4_4_kilo_model_routing_preferences.sql',
        sql: `
CREATE TABLE IF NOT EXISTS kilo_model_routing_preferences (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL CHECK (provider_id = 'kilo'),
    model_id TEXT NOT NULL,
    routing_mode TEXT NOT NULL CHECK (routing_mode IN ('dynamic', 'pinned')),
    sort TEXT NULL CHECK (sort IN ('default', 'price', 'throughput', 'latency')),
    pinned_provider_id TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, model_id),
    CHECK (
        (routing_mode = 'dynamic' AND sort IS NOT NULL AND pinned_provider_id IS NULL)
        OR
        (routing_mode = 'pinned' AND sort IS NULL AND pinned_provider_id IS NOT NULL)
    )
);
`,
    },
];
