// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.

export interface RuntimeSqlMigration {
    name: string;
    sql: string;
}

export const runtimeSqlMigrations: RuntimeSqlMigration[] = [
    {
        name: '001_runtime_baseline.sql',
        sql: `
-- NeonConductor alpha re-baseline.
-- This file is the current canonical runtime schema and intentionally replaces the older
-- step-by-step migration history. Existing local alpha databases should be recreated
-- instead of trying to reconcile the old migration names with this re-baseline.

-- Core profiles, settings, and runtime metadata.
CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1))
);

CREATE TABLE settings (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE runtime_events (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL,
    domain TEXT NOT NULL,
    operation TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE app_context_settings (
    id TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    mode TEXT NOT NULL CHECK (mode IN ('percent')),
    percent INTEGER NOT NULL CHECK (percent BETWEEN 1 AND 100),
    updated_at TEXT NOT NULL
);

CREATE TABLE app_prompt_layer_settings (
    id TEXT PRIMARY KEY,
    global_instructions TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE built_in_mode_prompt_overrides (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    top_level_tab TEXT NOT NULL,
    mode_key TEXT NOT NULL,
    prompt_json TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, top_level_tab, mode_key)
);

CREATE TABLE app_composer_media_settings (
    id TEXT PRIMARY KEY,
    max_image_attachments_per_message INTEGER NOT NULL,
    image_compression_concurrency INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE profile_context_settings (
    profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    override_mode TEXT NOT NULL CHECK (override_mode IN ('inherit', 'percent', 'fixed_tokens')),
    percent INTEGER NULL CHECK (percent IS NULL OR percent BETWEEN 1 AND 100),
    fixed_input_tokens INTEGER NULL CHECK (fixed_input_tokens IS NULL OR fixed_input_tokens > 0),
    updated_at TEXT NOT NULL
);

CREATE TABLE providers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    supports_byok INTEGER NOT NULL CHECK (supports_byok IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE model_limit_overrides (
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    context_length INTEGER NULL CHECK (context_length IS NULL OR context_length > 0),
    max_output_tokens INTEGER NULL CHECK (max_output_tokens IS NULL OR max_output_tokens > 0),
    reason TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (provider_id, model_id),
    CHECK (context_length IS NOT NULL OR max_output_tokens IS NOT NULL)
);

-- Providers, auth, catalog, and routing.
CREATE TABLE provider_models (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE provider_auth_states (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    auth_method TEXT NOT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    auth_state TEXT NOT NULL CHECK (auth_state IN ('logged_out', 'pending', 'configured', 'authenticated', 'error', 'expired')),
    account_id TEXT NULL,
    organization_id TEXT NULL,
    token_expires_at TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id)
);

CREATE TABLE provider_auth_flows (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    flow_type TEXT NOT NULL CHECK (flow_type IN ('device_code', 'oauth_pkce', 'oauth_device')),
    auth_method TEXT NOT NULL CHECK (auth_method IN ('device_code', 'oauth_pkce', 'oauth_device')),
    nonce TEXT NULL,
    state TEXT NULL,
    code_verifier TEXT NULL,
    redirect_uri TEXT NULL,
    device_code TEXT NULL,
    user_code TEXT NULL,
    verification_uri TEXT NULL,
    poll_interval_seconds INTEGER NULL,
    expires_at TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'cancelled', 'expired', 'failed')),
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    consumed_at TEXT NULL
);

CREATE TABLE provider_discovery_snapshots (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    etag TEXT NULL,
    payload_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, kind)
);

CREATE TABLE provider_model_catalog (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    label TEXT NOT NULL,
    upstream_provider TEXT NULL,
    is_free INTEGER NOT NULL CHECK (is_free IN (0, 1)),
    supports_tools INTEGER NOT NULL CHECK (supports_tools IN (0, 1)),
    supports_reasoning INTEGER NOT NULL CHECK (supports_reasoning IN (0, 1)),
    context_length INTEGER NULL,
    pricing_json TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    source TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    supports_vision INTEGER NULL CHECK (supports_vision IN (0, 1)),
    supports_audio_input INTEGER NULL CHECK (supports_audio_input IN (0, 1)),
    supports_audio_output INTEGER NULL CHECK (supports_audio_output IN (0, 1)),
    input_modalities_json TEXT NULL,
    output_modalities_json TEXT NULL,
    prompt_family TEXT NULL,
    supports_prompt_cache INTEGER NULL CHECK (supports_prompt_cache IN (0, 1)),
    tool_protocol TEXT NULL CHECK (
        tool_protocol IN (
            'openai_responses',
            'openai_chat_completions',
            'kilo_gateway',
            'provider_native',
            'anthropic_messages',
            'google_generativeai'
        )
    ),
    api_family TEXT NULL CHECK (
        api_family IN (
            'openai_compatible',
            'kilo_gateway',
            'provider_native',
            'anthropic_messages',
            'google_generativeai'
        )
    ),
    provider_settings_json TEXT NULL,
    routed_api_family TEXT NULL CHECK (
        routed_api_family IN (
            'openai_compatible',
            'provider_native',
            'anthropic_messages',
            'google_generativeai'
        )
    ),
    PRIMARY KEY (profile_id, provider_id, model_id)
);

CREATE TABLE provider_secrets (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    secret_kind TEXT NOT NULL,
    secret_value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE kilo_account_snapshots (
    profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    account_id TEXT NULL,
    display_name TEXT NOT NULL,
    email_masked TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    token_expires_at TEXT NULL,
    updated_at TEXT NOT NULL,
    balance_amount REAL NULL,
    balance_currency TEXT NULL,
    balance_updated_at TEXT NULL
);

CREATE TABLE kilo_org_snapshots (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL CHECK (is_active IN (0, 1)),
    entitlement_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE kilo_model_routing_preferences (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL CHECK (provider_id = 'kilo'),
    model_id TEXT NOT NULL,
    routing_mode TEXT NOT NULL CHECK (routing_mode IN ('dynamic', 'pinned')),
    sort TEXT NULL CHECK (sort IN ('default', 'price', 'throughput', 'latency')),
    pinned_provider_id TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, model_id),
    CHECK (
        (routing_mode = 'dynamic' AND sort IS NOT NULL AND pinned_provider_id IS NULL)
        OR
        (routing_mode = 'pinned' AND sort IS NULL AND pinned_provider_id IS NOT NULL)
    )
);

-- Conversations, workspace state, sessions, and runs.
CREATE TABLE conversations (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    scope TEXT NOT NULL CHECK (scope IN ('detached', 'workspace')),
    workspace_fingerprint TEXT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE workspace_roots (
    fingerprint TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    absolute_path TEXT NOT NULL,
    path_key TEXT NOT NULL,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE sandboxes (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workspace_fingerprint TEXT NOT NULL REFERENCES workspace_roots(fingerprint) ON DELETE CASCADE,
    absolute_path TEXT NOT NULL,
    path_key TEXT NOT NULL,
    label TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'ready', 'missing', 'broken', 'removed')),
    creation_strategy TEXT NOT NULL CHECK (creation_strategy IN ('clone', 'copy')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_used_at TEXT NOT NULL
);

CREATE TABLE threads (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    top_level_tab TEXT NOT NULL CHECK (top_level_tab IN ('chat', 'agent', 'orchestrator')),
    parent_thread_id TEXT NULL REFERENCES threads(id) ON DELETE SET NULL,
    root_thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    delegated_from_orchestrator_run_id TEXT NULL,
    last_assistant_at TEXT NULL,
    execution_environment_mode TEXT NOT NULL DEFAULT 'local',
    sandbox_id TEXT NULL REFERENCES sandboxes(id) ON DELETE SET NULL,
    is_favorite INTEGER NOT NULL DEFAULT 0 CHECK (is_favorite IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE tags (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE thread_tags (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, thread_id, tag_id)
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('local', 'sandbox', 'cloud')),
    sandbox_id TEXT NULL REFERENCES sandboxes(id) ON DELETE SET NULL,
    delegated_from_orchestrator_run_id TEXT NULL,
    run_status TEXT NOT NULL CHECK (run_status IN ('idle', 'running', 'completed', 'aborted', 'error')),
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE runs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    provider_id TEXT NULL REFERENCES providers(id) ON DELETE SET NULL,
    model_id TEXT NULL,
    auth_method TEXT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    reasoning_effort TEXT NULL CHECK (reasoning_effort IN ('none', 'minimal', 'low', 'medium', 'high', 'xhigh')),
    reasoning_summary TEXT NULL CHECK (reasoning_summary IN ('auto', 'none')),
    reasoning_include_encrypted INTEGER NULL CHECK (reasoning_include_encrypted IN (0, 1)),
    cache_strategy TEXT NULL CHECK (cache_strategy IN ('auto', 'manual')),
    cache_key TEXT NULL,
    cache_applied INTEGER NULL CHECK (cache_applied IN (0, 1)),
    cache_skip_reason TEXT NULL,
    transport_requested_family TEXT NULL CHECK (transport_requested_family IN ('auto', 'openai_responses', 'openai_chat_completions')),
    transport_selected TEXT NULL CHECK (
        transport_selected IN (
            'openai_responses',
            'openai_chat_completions',
            'openai_realtime_websocket',
            'kilo_gateway',
            'provider_native',
            'anthropic_messages',
            'google_generativeai'
        )
    ),
    transport_degraded_reason TEXT NULL,
    started_at TEXT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE run_usage (
    run_id TEXT PRIMARY KEY REFERENCES runs(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    input_tokens INTEGER NULL,
    output_tokens INTEGER NULL,
    cached_tokens INTEGER NULL,
    reasoning_tokens INTEGER NULL,
    total_tokens INTEGER NULL,
    latency_ms INTEGER NULL,
    cost_microunits INTEGER NULL,
    billed_via TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE messages (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE message_parts (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    part_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE message_media (
    media_id TEXT PRIMARY KEY,
    message_part_id TEXT NOT NULL UNIQUE REFERENCES message_parts(id) ON DELETE CASCADE,
    mime_type TEXT NOT NULL,
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
    sha256 TEXT NOT NULL,
    bytes_blob BLOB NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE session_context_compactions (
    session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    cutoff_message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    summary_text TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('auto', 'manual')),
    threshold_tokens INTEGER NOT NULL,
    estimated_input_tokens INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE diffs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    artifact_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE checkpoints (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    run_id TEXT NULL,
    diff_id TEXT NULL,
    workspace_fingerprint TEXT NOT NULL,
    sandbox_id TEXT NULL REFERENCES sandboxes(id) ON DELETE SET NULL,
    execution_target_key TEXT NOT NULL,
    execution_target_kind TEXT NOT NULL CHECK (execution_target_kind IN ('workspace', 'sandbox')),
    execution_target_label TEXT NOT NULL,
    created_by_kind TEXT NOT NULL CHECK (created_by_kind IN ('system', 'user')),
    checkpoint_kind TEXT NOT NULL CHECK (checkpoint_kind IN ('auto', 'safety', 'named')),
    milestone_title TEXT NULL,
    snapshot_file_count INTEGER NOT NULL CHECK (snapshot_file_count >= 0),
    top_level_tab TEXT NOT NULL,
    mode_key TEXT NOT NULL,
    summary TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (thread_id) REFERENCES threads(id) ON DELETE CASCADE,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    FOREIGN KEY (diff_id) REFERENCES diffs(id) ON DELETE SET NULL
);

CREATE TABLE checkpoint_snapshot_blobs (
    sha256 TEXT PRIMARY KEY,
    byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
    storage_state TEXT NOT NULL CHECK (storage_state IN ('inline', 'packed')),
    bytes_blob BLOB NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (
        (storage_state = 'inline' AND bytes_blob IS NOT NULL)
        OR
        (storage_state = 'packed' AND bytes_blob IS NULL)
    )
);

CREATE TABLE checkpoint_blob_packs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    trigger_kind TEXT NOT NULL CHECK (trigger_kind IN ('automatic', 'manual')),
    compression_kind TEXT NOT NULL CHECK (compression_kind IN ('brotli')),
    blob_count INTEGER NOT NULL CHECK (blob_count >= 0),
    original_byte_size INTEGER NOT NULL CHECK (original_byte_size >= 0),
    packed_byte_size INTEGER NOT NULL CHECK (packed_byte_size >= 0),
    pack_bytes_blob BLOB NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE checkpoint_blob_pack_members (
    blob_sha256 TEXT PRIMARY KEY REFERENCES checkpoint_snapshot_blobs(sha256) ON DELETE CASCADE,
    pack_id TEXT NOT NULL REFERENCES checkpoint_blob_packs(id) ON DELETE CASCADE,
    byte_offset INTEGER NOT NULL CHECK (byte_offset >= 0),
    compressed_byte_size INTEGER NOT NULL CHECK (compressed_byte_size > 0),
    original_byte_size INTEGER NOT NULL CHECK (original_byte_size >= 0),
    compression_kind TEXT NOT NULL CHECK (compression_kind IN ('brotli')),
    created_at TEXT NOT NULL
);

CREATE TABLE checkpoint_compaction_runs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    trigger_kind TEXT NOT NULL CHECK (trigger_kind IN ('automatic', 'manual')),
    status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'noop')),
    message TEXT NULL,
    blob_count_before INTEGER NOT NULL CHECK (blob_count_before >= 0),
    blob_count_after INTEGER NOT NULL CHECK (blob_count_after >= 0),
    bytes_before INTEGER NOT NULL CHECK (bytes_before >= 0),
    bytes_after INTEGER NOT NULL CHECK (bytes_after >= 0),
    blobs_compacted INTEGER NOT NULL CHECK (blobs_compacted >= 0),
    database_reclaimed INTEGER NOT NULL CHECK (database_reclaimed IN (0, 1)),
    started_at TEXT NOT NULL,
    completed_at TEXT NOT NULL
);

CREATE TABLE checkpoint_snapshot_entries (
    checkpoint_id TEXT NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    blob_sha256 TEXT NOT NULL REFERENCES checkpoint_snapshot_blobs(sha256) ON DELETE RESTRICT,
    byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
    created_at TEXT NOT NULL,
    PRIMARY KEY (checkpoint_id, relative_path)
);

CREATE TABLE checkpoint_changesets (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    checkpoint_id TEXT NOT NULL UNIQUE REFERENCES checkpoints(id) ON DELETE CASCADE,
    source_changeset_id TEXT NULL REFERENCES checkpoint_changesets(id) ON DELETE SET NULL,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs(id) ON DELETE CASCADE,
    execution_target_key TEXT NOT NULL,
    execution_target_kind TEXT NOT NULL CHECK (execution_target_kind IN ('workspace', 'sandbox')),
    execution_target_label TEXT NOT NULL,
    created_by_kind TEXT NOT NULL CHECK (created_by_kind IN ('system', 'user')),
    changeset_kind TEXT NOT NULL CHECK (changeset_kind IN ('run_capture', 'revert')),
    summary TEXT NOT NULL,
    change_count INTEGER NOT NULL CHECK (change_count >= 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE checkpoint_changeset_entries (
    changeset_id TEXT NOT NULL REFERENCES checkpoint_changesets(id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    change_kind TEXT NOT NULL CHECK (change_kind IN ('added', 'modified', 'deleted')),
    before_blob_sha256 TEXT NULL REFERENCES checkpoint_snapshot_blobs(sha256) ON DELETE RESTRICT,
    before_byte_size INTEGER NULL CHECK (before_byte_size IS NULL OR before_byte_size >= 0),
    after_blob_sha256 TEXT NULL REFERENCES checkpoint_snapshot_blobs(sha256) ON DELETE RESTRICT,
    after_byte_size INTEGER NULL CHECK (after_byte_size IS NULL OR after_byte_size >= 0),
    created_at TEXT NOT NULL,
    CHECK (
        (change_kind = 'added' AND before_blob_sha256 IS NULL AND before_byte_size IS NULL AND after_blob_sha256 IS NOT NULL AND after_byte_size IS NOT NULL) OR
        (change_kind = 'modified' AND before_blob_sha256 IS NOT NULL AND before_byte_size IS NOT NULL AND after_blob_sha256 IS NOT NULL AND after_byte_size IS NOT NULL) OR
        (change_kind = 'deleted' AND before_blob_sha256 IS NOT NULL AND before_byte_size IS NOT NULL AND after_blob_sha256 IS NULL AND after_byte_size IS NULL)
    ),
    PRIMARY KEY (changeset_id, relative_path)
);

-- Registry assets and session context attachments.
CREATE TABLE mode_definitions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    top_level_tab TEXT NOT NULL,
    mode_key TEXT NOT NULL,
    label TEXT NOT NULL,
    asset_key TEXT NOT NULL DEFAULT '',
    prompt_json TEXT NOT NULL,
    execution_policy_json TEXT NOT NULL,
    source TEXT NOT NULL,
    source_kind TEXT NOT NULL DEFAULT 'system_seed',
    scope TEXT NOT NULL DEFAULT 'system',
    workspace_fingerprint TEXT NULL,
    origin_path TEXT NULL,
    description TEXT NULL,
    when_to_use TEXT NULL,
    groups_json TEXT NOT NULL DEFAULT '[]',
    tags_json TEXT NOT NULL DEFAULT '[]',
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE rulesets (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    asset_key TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'workspace', 'session')),
    workspace_fingerprint TEXT NULL,
    preset_key TEXT NULL CHECK (preset_key IN ('ask', 'code', 'debug', 'orchestrator')),
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('system_seed', 'global_file', 'workspace_file', 'session_override')),
    origin_path TEXT NULL,
    description TEXT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    activation_mode TEXT NOT NULL CHECK (activation_mode IN ('always', 'auto', 'manual')),
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE skillfiles (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    asset_key TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('global', 'workspace', 'session')),
    workspace_fingerprint TEXT NULL,
    preset_key TEXT NULL CHECK (preset_key IN ('ask', 'code', 'debug', 'orchestrator')),
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    source_kind TEXT NOT NULL CHECK (source_kind IN ('system_seed', 'global_file', 'workspace_file', 'session_override')),
    origin_path TEXT NULL,
    description TEXT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE session_attached_skills (
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    asset_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (session_id, asset_key)
);

CREATE TABLE session_attached_rules (
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    asset_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (session_id, asset_key)
);

CREATE TABLE memory_records (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    memory_type TEXT NOT NULL CHECK (memory_type IN ('semantic', 'episodic', 'procedural')),
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('global', 'workspace', 'thread', 'run')),
    state TEXT NOT NULL CHECK (state IN ('active', 'disabled', 'superseded')),
    workspace_fingerprint TEXT NULL,
    thread_id TEXT NULL REFERENCES threads(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES runs(id) ON DELETE CASCADE,
    created_by_kind TEXT NOT NULL CHECK (created_by_kind IN ('user', 'system')),
    title TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    summary_text TEXT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    superseded_by_memory_id TEXT NULL REFERENCES memory_records(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK (
        (scope_kind = 'global' AND workspace_fingerprint IS NULL AND thread_id IS NULL AND run_id IS NULL) OR
        (scope_kind = 'workspace' AND workspace_fingerprint IS NOT NULL AND thread_id IS NULL AND run_id IS NULL) OR
        (scope_kind = 'thread' AND thread_id IS NOT NULL AND run_id IS NULL) OR
        (scope_kind = 'run' AND run_id IS NOT NULL)
    ),
    CHECK (
        (state = 'superseded' AND superseded_by_memory_id IS NOT NULL) OR
        (state IN ('active', 'disabled') AND superseded_by_memory_id IS NULL)
    )
);

CREATE TABLE memory_temporal_facts (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    subject_key TEXT NOT NULL,
    fact_kind TEXT NOT NULL CHECK (fact_kind IN ('semantic', 'episodic', 'procedural')),
    value_json TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('current', 'superseded', 'disabled')),
    valid_from TEXT NOT NULL,
    valid_to TEXT NULL,
    source_memory_id TEXT NOT NULL REFERENCES memory_records(id) ON DELETE CASCADE,
    source_run_id TEXT NULL REFERENCES runs(id) ON DELETE CASCADE,
    derivation_version INTEGER NOT NULL CHECK (derivation_version > 0),
    confidence REAL NULL CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE memory_causal_links (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    source_entity_kind TEXT NOT NULL CHECK (source_entity_kind IN ('memory', 'run', 'thread', 'workspace')),
    source_entity_id TEXT NOT NULL,
    target_entity_kind TEXT NOT NULL CHECK (target_entity_kind IN ('memory', 'run', 'thread', 'workspace')),
    target_entity_id TEXT NOT NULL,
    relation_type TEXT NOT NULL CHECK (
        relation_type IN (
            'derived_from',
            'caused_by',
            'supersedes',
            'observed_in_run',
            'observed_in_thread',
            'observed_in_workspace'
        )
    ),
    source_memory_id TEXT NOT NULL REFERENCES memory_records(id) ON DELETE CASCADE,
    source_run_id TEXT NULL REFERENCES runs(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Planning and orchestration.
CREATE TABLE plan_records (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    top_level_tab TEXT NOT NULL CHECK (top_level_tab IN ('chat', 'agent', 'orchestrator')),
    mode_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('awaiting_answers', 'draft', 'approved', 'implementing', 'implemented', 'failed', 'cancelled')),
    source_prompt TEXT NOT NULL,
    summary_markdown TEXT NOT NULL,
    questions_json TEXT NOT NULL DEFAULT '[]',
    answers_json TEXT NOT NULL DEFAULT '{}',
    workspace_fingerprint TEXT NULL,
    implementation_run_id TEXT NULL,
    orchestrator_run_id TEXT NULL,
    approved_at TEXT NULL,
    implemented_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (implementation_run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE TABLE plan_items (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (plan_id) REFERENCES plan_records(id) ON DELETE CASCADE,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE TABLE orchestrator_runs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'aborted', 'failed')),
    execution_strategy TEXT NOT NULL CHECK (execution_strategy IN ('delegate', 'parallel')),
    active_step_index INTEGER NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES plan_records(id) ON DELETE CASCADE
);

CREATE TABLE orchestrator_steps (
    id TEXT PRIMARY KEY,
    orchestrator_run_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    child_thread_id TEXT NULL REFERENCES threads(id) ON DELETE SET NULL,
    child_session_id TEXT NULL REFERENCES sessions(id) ON DELETE SET NULL,
    active_run_id TEXT NULL REFERENCES runs(id) ON DELETE SET NULL,
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (orchestrator_run_id) REFERENCES orchestrator_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL
);

-- Permissions, tools, MCP, and marketplace.
CREATE TABLE permission_policy_overrides (
    profile_id TEXT NOT NULL,
    scope_key TEXT NOT NULL,
    resource TEXT NOT NULL,
    policy TEXT NOT NULL CHECK (policy IN ('ask', 'allow', 'deny')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, scope_key, resource)
);

CREATE TABLE permissions (
    id TEXT PRIMARY KEY,
    policy TEXT NOT NULL,
    resource TEXT NOT NULL,
    tool_id TEXT NOT NULL DEFAULT '',
    workspace_fingerprint TEXT NULL,
    scope_kind TEXT NOT NULL DEFAULT 'tool',
    summary_json TEXT NOT NULL DEFAULT '{"title":"Permission Request","detail":"This action requires approval."}',
    command_text TEXT NULL,
    approval_candidates_json TEXT NOT NULL DEFAULT '[]',
    selected_approval_resource TEXT NULL,
    decision TEXT NOT NULL,
    resolved_scope TEXT NULL,
    consumed_at TEXT NULL,
    rationale TEXT NULL,
    profile_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE tools_catalog (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL,
    permission_policy TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE mcp_servers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    auth_mode TEXT NOT NULL,
    connection_state TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE marketplace_packages (
    id TEXT PRIMARY KEY,
    package_kind TEXT NOT NULL,
    slug TEXT NOT NULL,
    version TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    pinned INTEGER NOT NULL CHECK (pinned IN (0, 1)),
    source_json TEXT NOT NULL,
    installed_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE marketplace_assets (
    package_id TEXT NOT NULL REFERENCES marketplace_packages(id) ON DELETE CASCADE,
    asset_kind TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (package_id, asset_kind, asset_id)
);

-- Default singleton rows for runtime settings.
INSERT INTO app_context_settings (id, enabled, mode, percent, updated_at)
VALUES ('global', 1, 'percent', 90, CURRENT_TIMESTAMP);

INSERT INTO app_prompt_layer_settings (id, global_instructions, updated_at)
VALUES ('global', '', CURRENT_TIMESTAMP);

INSERT INTO app_composer_media_settings (id, max_image_attachments_per_message, image_compression_concurrency, updated_at)
VALUES ('global', 10, 2, CURRENT_TIMESTAMP);

-- Indexes.
CREATE UNIQUE INDEX idx_profiles_single_active
    ON profiles(is_active)
    WHERE is_active = 1;

CREATE UNIQUE INDEX idx_settings_profile_key
    ON settings(profile_id, key);

CREATE INDEX idx_runtime_events_sequence
    ON runtime_events(sequence);

CREATE INDEX idx_model_limit_overrides_provider_updated_at
    ON model_limit_overrides(provider_id, updated_at DESC);

CREATE INDEX idx_provider_auth_flows_expires_at
    ON provider_auth_flows(expires_at);

CREATE UNIQUE INDEX idx_provider_auth_flows_profile_provider_state
    ON provider_auth_flows(profile_id, provider_id, state);

CREATE INDEX idx_provider_auth_flows_profile_provider_status
    ON provider_auth_flows(profile_id, provider_id, status);

CREATE INDEX idx_provider_model_catalog_profile_provider_label
    ON provider_model_catalog(profile_id, provider_id, label);

CREATE INDEX idx_provider_models_provider_id
    ON provider_models(provider_id);

CREATE UNIQUE INDEX idx_provider_secrets_profile_provider_kind
    ON provider_secrets(profile_id, provider_id, secret_kind);

CREATE UNIQUE INDEX idx_kilo_org_snapshots_profile_org
    ON kilo_org_snapshots(profile_id, organization_id);

CREATE INDEX idx_conversations_profile_scope_updated_at
    ON conversations(profile_id, scope, updated_at DESC);

CREATE UNIQUE INDEX idx_conversations_profile_scope_workspace
    ON conversations(profile_id, scope, ifnull(workspace_fingerprint, ''));

CREATE UNIQUE INDEX idx_workspace_roots_profile_path_key
    ON workspace_roots(profile_id, path_key);

CREATE INDEX idx_workspace_roots_profile_updated_at
    ON workspace_roots(profile_id, updated_at DESC);

CREATE UNIQUE INDEX idx_sandboxes_profile_path_key
    ON sandboxes(profile_id, path_key);

CREATE UNIQUE INDEX idx_sandboxes_profile_workspace_label
    ON sandboxes(profile_id, workspace_fingerprint, label);

CREATE INDEX idx_sandboxes_profile_workspace_updated_at
    ON sandboxes(profile_id, workspace_fingerprint, updated_at DESC);

CREATE INDEX idx_threads_profile_conversation_updated_at
    ON threads(profile_id, conversation_id, updated_at DESC);

CREATE INDEX idx_threads_profile_last_assistant_at
    ON threads(profile_id, last_assistant_at DESC, updated_at DESC);

CREATE INDEX idx_threads_profile_mode_updated_at
    ON threads(profile_id, top_level_tab, updated_at DESC);

CREATE INDEX idx_threads_delegated_orchestrator_run_id
    ON threads(delegated_from_orchestrator_run_id);

CREATE INDEX idx_threads_profile_parent_updated_at
    ON threads(profile_id, parent_thread_id, updated_at DESC);

CREATE INDEX idx_threads_profile_root_updated_at
    ON threads(profile_id, root_thread_id, updated_at DESC);

CREATE INDEX idx_threads_profile_sandbox_updated_at
    ON threads(profile_id, sandbox_id, updated_at DESC);

CREATE UNIQUE INDEX idx_tags_profile_label
    ON tags(profile_id, label);

CREATE INDEX idx_thread_tags_profile_tag
    ON thread_tags(profile_id, tag_id);

CREATE INDEX idx_thread_tags_profile_thread
    ON thread_tags(profile_id, thread_id);

CREATE INDEX idx_sessions_profile_conversation_updated_at
    ON sessions(profile_id, conversation_id, updated_at DESC);

CREATE INDEX idx_sessions_profile_thread_updated_at
    ON sessions(profile_id, thread_id, updated_at DESC);

CREATE INDEX idx_sessions_delegated_orchestrator_run_id
    ON sessions(delegated_from_orchestrator_run_id);

CREATE INDEX idx_sessions_profile_sandbox_updated_at
    ON sessions(profile_id, sandbox_id, updated_at DESC);

CREATE INDEX idx_runs_profile_created_at
    ON runs(profile_id, created_at DESC);

CREATE INDEX idx_runs_profile_status
    ON runs(profile_id, status);

CREATE INDEX idx_runs_session_id_created_at
    ON runs(session_id, created_at DESC);

CREATE INDEX idx_run_usage_provider_recorded_at
    ON run_usage(provider_id, recorded_at DESC);

CREATE INDEX idx_messages_profile_session_created_at
    ON messages(profile_id, session_id, created_at ASC);

CREATE INDEX idx_messages_run_created_at
    ON messages(run_id, created_at ASC);

CREATE INDEX idx_message_parts_created_at
    ON message_parts(created_at);

CREATE UNIQUE INDEX idx_message_parts_message_sequence
    ON message_parts(message_id, sequence);

CREATE INDEX idx_message_media_part_id
    ON message_media(message_part_id);

CREATE INDEX idx_session_context_compactions_profile_session
    ON session_context_compactions(profile_id, session_id);

CREATE INDEX idx_diffs_profile_session_created_at
    ON diffs(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_checkpoints_profile_run
    ON checkpoints(profile_id, run_id);

CREATE INDEX idx_checkpoints_profile_session_created_at
    ON checkpoints(profile_id, session_id, created_at DESC);

CREATE INDEX idx_checkpoints_profile_target_created_at
    ON checkpoints(profile_id, execution_target_key, created_at DESC);

CREATE INDEX idx_checkpoints_profile_thread_created_at
    ON checkpoints(profile_id, thread_id, created_at DESC);

CREATE INDEX idx_checkpoint_snapshot_entries_blob_sha256
    ON checkpoint_snapshot_entries(blob_sha256);

CREATE INDEX idx_checkpoint_snapshot_blobs_storage_state
    ON checkpoint_snapshot_blobs(storage_state);

CREATE INDEX idx_checkpoint_blob_packs_profile_created_at
    ON checkpoint_blob_packs(profile_id, created_at DESC);

CREATE INDEX idx_checkpoint_blob_pack_members_pack_id
    ON checkpoint_blob_pack_members(pack_id);

CREATE INDEX idx_checkpoint_compaction_runs_profile_completed_at
    ON checkpoint_compaction_runs(profile_id, completed_at DESC);

CREATE INDEX idx_checkpoint_changesets_profile_target_created_at
    ON checkpoint_changesets(profile_id, execution_target_key, created_at DESC);

CREATE INDEX idx_checkpoint_changesets_profile_session_created_at
    ON checkpoint_changesets(profile_id, session_id, created_at DESC);

CREATE INDEX idx_checkpoint_changesets_source_changeset_id
    ON checkpoint_changesets(source_changeset_id);

CREATE INDEX idx_checkpoint_changeset_entries_before_blob_sha256
    ON checkpoint_changeset_entries(before_blob_sha256);

CREATE INDEX idx_checkpoint_changeset_entries_after_blob_sha256
    ON checkpoint_changeset_entries(after_blob_sha256);

CREATE UNIQUE INDEX idx_mode_definitions_profile_registry_asset
    ON mode_definitions(profile_id, top_level_tab, scope, ifnull(workspace_fingerprint, ''), asset_key);

CREATE INDEX idx_mode_definitions_profile_tab_scope
    ON mode_definitions(profile_id, top_level_tab, scope, workspace_fingerprint);

CREATE UNIQUE INDEX idx_rulesets_profile_registry_asset
    ON rulesets(profile_id, scope, ifnull(workspace_fingerprint, ''), asset_key);

CREATE INDEX idx_rulesets_profile_scope
    ON rulesets(profile_id, scope, workspace_fingerprint);

CREATE INDEX idx_rulesets_workspace_fingerprint
    ON rulesets(workspace_fingerprint);

CREATE UNIQUE INDEX idx_skillfiles_profile_registry_asset
    ON skillfiles(profile_id, scope, ifnull(workspace_fingerprint, ''), asset_key);

CREATE INDEX idx_skillfiles_profile_scope
    ON skillfiles(profile_id, scope, workspace_fingerprint);

CREATE INDEX idx_skillfiles_workspace_fingerprint
    ON skillfiles(workspace_fingerprint);

CREATE INDEX idx_session_attached_skills_profile_session
    ON session_attached_skills(profile_id, session_id, created_at);

CREATE INDEX idx_session_attached_rules_profile_session
    ON session_attached_rules(profile_id, session_id, created_at);

CREATE INDEX idx_memory_records_profile_type_state
    ON memory_records(profile_id, memory_type, state);

CREATE INDEX idx_memory_records_profile_scope
    ON memory_records(profile_id, scope_kind);

CREATE INDEX idx_memory_records_profile_workspace
    ON memory_records(profile_id, workspace_fingerprint);

CREATE INDEX idx_memory_records_profile_thread
    ON memory_records(profile_id, thread_id);

CREATE INDEX idx_memory_records_profile_run
    ON memory_records(profile_id, run_id);

CREATE UNIQUE INDEX idx_memory_temporal_facts_profile_source_memory
    ON memory_temporal_facts(profile_id, source_memory_id);

CREATE INDEX idx_memory_temporal_facts_profile_subject_status
    ON memory_temporal_facts(profile_id, subject_key, status);

CREATE INDEX idx_memory_temporal_facts_profile_source_run
    ON memory_temporal_facts(profile_id, source_run_id);

CREATE UNIQUE INDEX idx_memory_causal_links_profile_unique_relation
    ON memory_causal_links(
        profile_id,
        source_memory_id,
        relation_type,
        source_entity_kind,
        source_entity_id,
        target_entity_kind,
        target_entity_id
    );

CREATE INDEX idx_memory_causal_links_profile_target_relation
    ON memory_causal_links(profile_id, target_entity_kind, target_entity_id, relation_type);

CREATE INDEX idx_memory_causal_links_profile_source_run
    ON memory_causal_links(profile_id, source_run_id, relation_type);

CREATE INDEX idx_plan_records_profile_session
    ON plan_records(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_plan_items_plan_sequence
    ON plan_items(plan_id, sequence);

CREATE INDEX idx_orchestrator_runs_profile_session
    ON orchestrator_runs(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_orchestrator_steps_run_sequence
    ON orchestrator_steps(orchestrator_run_id, sequence);

CREATE INDEX idx_permission_policy_overrides_scope
    ON permission_policy_overrides(profile_id, scope_key);

CREATE INDEX idx_permissions_decision_created_at
    ON permissions(decision, created_at);

CREATE INDEX idx_permissions_profile_decision_created_at
    ON permissions(profile_id, decision, created_at);

CREATE INDEX idx_permissions_resource_workspace_decision
    ON permissions(resource, workspace_fingerprint, decision);

CREATE UNIQUE INDEX idx_marketplace_packages_kind_slug
    ON marketplace_packages(package_kind, slug);
`,
    },
];
