// Auto-generated by scripts/generate-migrations.ts. Do not edit manually.

export interface RuntimeSqlMigration {
    name: string;
    sql: string;
}

export const runtimeSqlMigrations: RuntimeSqlMigration[] = [
    {
        name: '001_runtime_baseline_v4.sql',
        sql: `
CREATE TABLE "conversations" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    scope TEXT NOT NULL CHECK (scope IN ('detached', 'workspace')),
    workspace_fingerprint TEXT NULL,
    title TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "diffs" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES "sessions"(id) ON DELETE CASCADE,
    run_id TEXT NULL REFERENCES "runs"(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE kilo_account_snapshots (
    profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    account_id TEXT NULL,
    display_name TEXT NOT NULL,
    email_masked TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    token_expires_at TEXT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE kilo_model_routing_preferences (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL CHECK (provider_id = 'kilo'),
    model_id TEXT NOT NULL,
    routing_mode TEXT NOT NULL CHECK (routing_mode IN ('dynamic', 'pinned')),
    sort TEXT NULL CHECK (sort IN ('default', 'price', 'throughput', 'latency')),
    pinned_provider_id TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, model_id),
    CHECK (
        (routing_mode = 'dynamic' AND sort IS NOT NULL AND pinned_provider_id IS NULL)
        OR
        (routing_mode = 'pinned' AND sort IS NULL AND pinned_provider_id IS NOT NULL)
    )
);

CREATE TABLE kilo_org_snapshots (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL CHECK (is_active IN (0, 1)),
    entitlement_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE marketplace_assets (
    package_id TEXT NOT NULL REFERENCES marketplace_packages(id) ON DELETE CASCADE,
    asset_kind TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (package_id, asset_kind, asset_id)
);

CREATE TABLE marketplace_packages (
    id TEXT PRIMARY KEY,
    package_kind TEXT NOT NULL,
    slug TEXT NOT NULL,
    version TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    pinned INTEGER NOT NULL CHECK (pinned IN (0, 1)),
    source_json TEXT NOT NULL,
    installed_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE mcp_servers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    auth_mode TEXT NOT NULL,
    connection_state TEXT NOT NULL,
    auth_state TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "message_parts" (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL REFERENCES "messages"(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL,
    part_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE "messages" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES "sessions"(id) ON DELETE CASCADE,
    run_id TEXT NOT NULL REFERENCES "runs"(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE mode_definitions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    top_level_tab TEXT NOT NULL,
    mode_key TEXT NOT NULL,
    label TEXT NOT NULL,
    prompt_json TEXT NOT NULL,
    execution_policy_json TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE orchestrator_runs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'aborted', 'failed')),
    active_step_index INTEGER NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(plan_id) REFERENCES plan_records(id) ON DELETE CASCADE
);

CREATE TABLE orchestrator_steps (
    id TEXT PRIMARY KEY,
    orchestrator_run_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(orchestrator_run_id) REFERENCES orchestrator_runs(id) ON DELETE CASCADE,
    FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE TABLE permission_policy_overrides (
    profile_id TEXT NOT NULL,
    scope_key TEXT NOT NULL,
    resource TEXT NOT NULL,
    policy TEXT NOT NULL CHECK (policy IN ('ask', 'allow', 'deny')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, scope_key, resource)
);

CREATE TABLE permissions (
    id TEXT PRIMARY KEY,
    policy TEXT NOT NULL,
    resource TEXT NOT NULL,
    decision TEXT NOT NULL,
    rationale TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE plan_items (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'aborted')),
    run_id TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(plan_id) REFERENCES plan_records(id) ON DELETE CASCADE,
    FOREIGN KEY(run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE TABLE plan_records (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    top_level_tab TEXT NOT NULL CHECK (top_level_tab IN ('chat', 'agent', 'orchestrator')),
    mode_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('awaiting_answers', 'draft', 'approved', 'implementing', 'implemented', 'failed', 'cancelled')),
    source_prompt TEXT NOT NULL,
    summary_markdown TEXT NOT NULL,
    questions_json TEXT NOT NULL DEFAULT '[]',
    answers_json TEXT NOT NULL DEFAULT '{}',
    workspace_fingerprint TEXT NULL,
    implementation_run_id TEXT NULL,
    orchestrator_run_id TEXT NULL,
    approved_at TEXT NULL,
    implemented_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(implementation_run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1))
);

CREATE TABLE provider_auth_flows (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    flow_type TEXT NOT NULL CHECK (flow_type IN ('device_code', 'oauth_pkce', 'oauth_device')),
    auth_method TEXT NOT NULL CHECK (auth_method IN ('device_code', 'oauth_pkce', 'oauth_device')),
    nonce TEXT NULL,
    state TEXT NULL,
    code_verifier TEXT NULL,
    redirect_uri TEXT NULL,
    device_code TEXT NULL,
    user_code TEXT NULL,
    verification_uri TEXT NULL,
    poll_interval_seconds INTEGER NULL,
    expires_at TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'cancelled', 'expired', 'failed')),
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    consumed_at TEXT NULL
);

CREATE TABLE "provider_auth_states" (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    auth_method TEXT NOT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    auth_state TEXT NOT NULL CHECK (auth_state IN ('logged_out', 'pending', 'configured', 'authenticated', 'error', 'expired')),
    account_id TEXT NULL,
    organization_id TEXT NULL,
    token_expires_at TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id)
);

CREATE TABLE provider_discovery_snapshots (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    etag TEXT NULL,
    payload_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    status TEXT NOT NULL,
    PRIMARY KEY (profile_id, provider_id, kind)
);

CREATE TABLE provider_model_catalog (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    label TEXT NOT NULL,
    upstream_provider TEXT NULL,
    is_free INTEGER NOT NULL CHECK (is_free IN (0, 1)),
    supports_tools INTEGER NOT NULL CHECK (supports_tools IN (0, 1)),
    supports_reasoning INTEGER NOT NULL CHECK (supports_reasoning IN (0, 1)),
    context_length INTEGER NULL,
    pricing_json TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    source TEXT NOT NULL,
    updated_at TEXT NOT NULL, supports_vision INTEGER NULL
    CHECK (supports_vision IN (0, 1)), supports_audio_input INTEGER NULL
    CHECK (supports_audio_input IN (0, 1)), supports_audio_output INTEGER NULL
    CHECK (supports_audio_output IN (0, 1)), input_modalities_json TEXT NULL, output_modalities_json TEXT NULL, prompt_family TEXT NULL,
    PRIMARY KEY (profile_id, provider_id, model_id)
);

CREATE TABLE provider_models (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE providers (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    supports_byok INTEGER NOT NULL CHECK (supports_byok IN (0, 1)),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE rulesets (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workspace_fingerprint TEXT NULL,
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "run_usage" (
    run_id TEXT PRIMARY KEY REFERENCES "runs"(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    model_id TEXT NOT NULL,
    input_tokens INTEGER NULL,
    output_tokens INTEGER NULL,
    cached_tokens INTEGER NULL,
    reasoning_tokens INTEGER NULL,
    total_tokens INTEGER NULL,
    latency_ms INTEGER NULL,
    cost_microunits INTEGER NULL,
    billed_via TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE "runs" (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES "sessions"(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    provider_id TEXT NULL REFERENCES providers(id) ON DELETE SET NULL,
    model_id TEXT NULL,
    auth_method TEXT NULL CHECK (auth_method IN ('none', 'api_key', 'device_code', 'oauth_pkce', 'oauth_device')),
    reasoning_effort TEXT NULL CHECK (reasoning_effort IN ('none', 'minimal', 'low', 'medium', 'high', 'xhigh')),
    reasoning_summary TEXT NULL CHECK (reasoning_summary IN ('auto', 'none')),
    reasoning_include_encrypted INTEGER NULL CHECK (reasoning_include_encrypted IN (0, 1)),
    cache_strategy TEXT NULL CHECK (cache_strategy IN ('auto', 'manual')),
    cache_key TEXT NULL,
    cache_applied INTEGER NULL CHECK (cache_applied IN (0, 1)),
    cache_skip_reason TEXT NULL,
    transport_openai_preference TEXT NULL CHECK (transport_openai_preference IN ('responses', 'chat', 'auto')),
    transport_selected TEXT NULL CHECK (transport_selected IN ('responses', 'chat_completions')),
    transport_degraded_reason TEXT NULL,
    started_at TEXT NULL,
    completed_at TEXT NULL,
    aborted_at TEXT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE runtime_events (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL UNIQUE,
    entity_type TEXT NOT NULL,
    domain TEXT NOT NULL,
    operation TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE secret_references (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL,
    secret_key_ref TEXT NOT NULL,
    secret_kind TEXT NOT NULL,
    status TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "sessions" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES "conversations"(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES "threads"(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('local', 'worktree', 'cloud')),
    run_status TEXT NOT NULL CHECK (run_status IN ('idle', 'running', 'completed', 'aborted', 'error')),
    pending_completion_run_id TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "settings" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE skillfiles (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    workspace_fingerprint TEXT NULL,
    name TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    source TEXT NOT NULL,
    enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
    precedence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "tags" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE "thread_tags" (
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    thread_id TEXT NOT NULL REFERENCES "threads"(id) ON DELETE CASCADE,
    tag_id TEXT NOT NULL REFERENCES "tags"(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (profile_id, thread_id, tag_id)
);

CREATE TABLE "threads" (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    top_level_tab TEXT NOT NULL CHECK (top_level_tab IN ('chat', 'agent', 'orchestrator')),
    parent_thread_id TEXT NULL REFERENCES "threads"(id) ON DELETE SET NULL,
    root_thread_id TEXT NOT NULL REFERENCES "threads"(id) ON DELETE CASCADE,
    last_assistant_at TEXT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE tools_catalog (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL,
    permission_policy TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_conversations_profile_scope_updated_at
    ON "conversations"(profile_id, scope, updated_at DESC);

CREATE UNIQUE INDEX idx_conversations_profile_scope_workspace
    ON "conversations"(profile_id, scope, ifnull(workspace_fingerprint, ''));

CREATE INDEX idx_diffs_profile_session_created_at
    ON "diffs"(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_kilo_org_snapshots_profile_org
    ON kilo_org_snapshots(profile_id, organization_id);

CREATE UNIQUE INDEX idx_marketplace_packages_kind_slug
    ON marketplace_packages(package_kind, slug);

CREATE INDEX idx_message_parts_created_at
    ON message_parts(created_at);

CREATE UNIQUE INDEX idx_message_parts_message_sequence
    ON message_parts(message_id, sequence);

CREATE INDEX idx_messages_profile_session_created_at
    ON messages(profile_id, session_id, created_at ASC);

CREATE INDEX idx_messages_run_created_at
    ON messages(run_id, created_at ASC);

CREATE UNIQUE INDEX idx_mode_definitions_profile_tab_mode
    ON mode_definitions(profile_id, top_level_tab, mode_key);

CREATE INDEX idx_orchestrator_runs_profile_session
    ON orchestrator_runs(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_orchestrator_steps_run_sequence
    ON orchestrator_steps(orchestrator_run_id, sequence);

CREATE INDEX idx_permission_policy_overrides_scope
    ON permission_policy_overrides(profile_id, scope_key);

CREATE INDEX idx_permissions_decision_created_at ON permissions(decision, created_at);

CREATE UNIQUE INDEX idx_plan_items_plan_sequence
    ON plan_items(plan_id, sequence);

CREATE INDEX idx_plan_records_profile_session
    ON plan_records(profile_id, session_id, created_at DESC);

CREATE UNIQUE INDEX idx_profiles_single_active
    ON profiles(is_active)
    WHERE is_active = 1;

CREATE INDEX idx_provider_auth_flows_expires_at
    ON provider_auth_flows(expires_at);

CREATE UNIQUE INDEX idx_provider_auth_flows_profile_provider_state
    ON provider_auth_flows(profile_id, provider_id, state);

CREATE INDEX idx_provider_auth_flows_profile_provider_status
    ON provider_auth_flows(profile_id, provider_id, status);

CREATE INDEX idx_provider_model_catalog_profile_provider_label
    ON provider_model_catalog(profile_id, provider_id, label);

CREATE INDEX idx_provider_models_provider_id ON provider_models(provider_id);

CREATE UNIQUE INDEX idx_rulesets_profile_scope_name
    ON rulesets(profile_id, ifnull(workspace_fingerprint, ''), name);

CREATE INDEX idx_rulesets_workspace_fingerprint
    ON rulesets(workspace_fingerprint);

CREATE INDEX idx_run_usage_provider_recorded_at
    ON run_usage(provider_id, recorded_at DESC);

CREATE INDEX idx_runs_profile_created_at
    ON runs(profile_id, created_at DESC);

CREATE INDEX idx_runs_profile_status
    ON runs(profile_id, status);

CREATE INDEX idx_runs_session_id_created_at
    ON runs(session_id, created_at DESC);

CREATE INDEX idx_runtime_events_sequence ON runtime_events(sequence);

CREATE UNIQUE INDEX idx_secret_references_profile_provider_kind
    ON secret_references(profile_id, provider_id, secret_kind);

CREATE INDEX idx_sessions_profile_conversation_updated_at
    ON "sessions"(profile_id, conversation_id, updated_at DESC);

CREATE INDEX idx_sessions_profile_thread_updated_at
    ON "sessions"(profile_id, thread_id, updated_at DESC);

CREATE UNIQUE INDEX idx_settings_profile_key
    ON settings(profile_id, key);

CREATE UNIQUE INDEX idx_skillfiles_profile_scope_name
    ON skillfiles(profile_id, ifnull(workspace_fingerprint, ''), name);

CREATE INDEX idx_skillfiles_workspace_fingerprint
    ON skillfiles(workspace_fingerprint);

CREATE UNIQUE INDEX idx_tags_profile_label
    ON "tags"(profile_id, label);

CREATE INDEX idx_thread_tags_profile_tag
    ON "thread_tags"(profile_id, tag_id);

CREATE INDEX idx_thread_tags_profile_thread
    ON "thread_tags"(profile_id, thread_id);

CREATE INDEX idx_threads_profile_conversation_updated_at
    ON threads(profile_id, conversation_id, updated_at DESC);

CREATE INDEX idx_threads_profile_last_assistant_at
    ON threads(profile_id, last_assistant_at DESC, updated_at DESC);

CREATE INDEX idx_threads_profile_mode_updated_at
    ON threads(profile_id, top_level_tab, updated_at DESC);

CREATE INDEX idx_threads_profile_parent_updated_at
    ON threads(profile_id, parent_thread_id, updated_at DESC);

CREATE INDEX idx_threads_profile_root_updated_at
    ON threads(profile_id, root_thread_id, updated_at DESC);
`,
    },
    {
        name: '002_kilo_account_balance.sql',
        sql: `
ALTER TABLE kilo_account_snapshots
    ADD COLUMN balance_amount REAL NULL;

ALTER TABLE kilo_account_snapshots
    ADD COLUMN balance_currency TEXT NULL;

ALTER TABLE kilo_account_snapshots
    ADD COLUMN balance_updated_at TEXT NULL;
`,
    },
    {
        name: '003_runtime_safety_foundation.sql',
        sql: `
ALTER TABLE permissions ADD COLUMN profile_id TEXT REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE permissions ADD COLUMN tool_id TEXT NOT NULL DEFAULT '';
ALTER TABLE permissions ADD COLUMN workspace_fingerprint TEXT NULL;
ALTER TABLE permissions ADD COLUMN scope_kind TEXT NOT NULL DEFAULT 'tool';
ALTER TABLE permissions ADD COLUMN summary_json TEXT NOT NULL DEFAULT '{"title":"Permission Request","detail":"This action requires approval."}';
ALTER TABLE permissions ADD COLUMN resolved_scope TEXT NULL;
ALTER TABLE permissions ADD COLUMN consumed_at TEXT NULL;

UPDATE permissions
SET
    profile_id = (
        SELECT id
        FROM profiles
        WHERE is_active = 1
        ORDER BY updated_at DESC, id ASC
        LIMIT 1
    )
WHERE profile_id IS NULL;

UPDATE permissions
SET tool_id = CASE
    WHEN resource LIKE 'tool:%' THEN substr(resource, 6, instr(substr(resource, 6), ':') - 1)
    ELSE ''
END
WHERE tool_id = '';

UPDATE permissions
SET tool_id = CASE
    WHEN tool_id = '' AND resource LIKE 'tool:%' THEN substr(resource, 6)
    ELSE tool_id
END
WHERE tool_id = '';

CREATE INDEX idx_permissions_profile_decision_created_at ON permissions(profile_id, decision, created_at);
CREATE INDEX idx_permissions_resource_workspace_decision ON permissions(resource, workspace_fingerprint, decision);

CREATE TABLE workspace_roots (
    fingerprint TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    absolute_path TEXT NOT NULL,
    path_key TEXT NOT NULL,
    label TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_workspace_roots_profile_path_key ON workspace_roots(profile_id, path_key);
CREATE INDEX idx_workspace_roots_profile_updated_at ON workspace_roots(profile_id, updated_at DESC);
`,
    },
    {
        name: '004_registry_metadata.sql',
        sql: `
ALTER TABLE mode_definitions ADD COLUMN asset_key TEXT NOT NULL DEFAULT '';
ALTER TABLE mode_definitions ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'system_seed';
ALTER TABLE mode_definitions ADD COLUMN scope TEXT NOT NULL DEFAULT 'system';
ALTER TABLE mode_definitions ADD COLUMN workspace_fingerprint TEXT NULL;
ALTER TABLE mode_definitions ADD COLUMN origin_path TEXT NULL;
ALTER TABLE mode_definitions ADD COLUMN description TEXT NULL;
ALTER TABLE mode_definitions ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE mode_definitions ADD COLUMN precedence INTEGER NOT NULL DEFAULT 0;

UPDATE mode_definitions
SET asset_key = mode_key
WHERE asset_key = '';

ALTER TABLE rulesets ADD COLUMN asset_key TEXT NOT NULL DEFAULT '';
ALTER TABLE rulesets ADD COLUMN scope TEXT NOT NULL DEFAULT 'workspace';
ALTER TABLE rulesets ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'session_override';
ALTER TABLE rulesets ADD COLUMN origin_path TEXT NULL;
ALTER TABLE rulesets ADD COLUMN description TEXT NULL;
ALTER TABLE rulesets ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]';

UPDATE rulesets
SET
    asset_key = lower(replace(name, ' ', '_')),
    scope = CASE
        WHEN workspace_fingerprint IS NULL THEN 'global'
        ELSE 'workspace'
    END,
    source_kind = CASE
        WHEN source = 'system' THEN 'system_seed'
        WHEN workspace_fingerprint IS NULL THEN 'global_file'
        ELSE 'workspace_file'
    END
WHERE asset_key = '';

ALTER TABLE skillfiles ADD COLUMN asset_key TEXT NOT NULL DEFAULT '';
ALTER TABLE skillfiles ADD COLUMN scope TEXT NOT NULL DEFAULT 'workspace';
ALTER TABLE skillfiles ADD COLUMN source_kind TEXT NOT NULL DEFAULT 'session_override';
ALTER TABLE skillfiles ADD COLUMN origin_path TEXT NULL;
ALTER TABLE skillfiles ADD COLUMN description TEXT NULL;
ALTER TABLE skillfiles ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]';

UPDATE skillfiles
SET
    asset_key = lower(replace(name, ' ', '_')),
    scope = CASE
        WHEN workspace_fingerprint IS NULL THEN 'global'
        ELSE 'workspace'
    END,
    source_kind = CASE
        WHEN source = 'system' THEN 'system_seed'
        WHEN workspace_fingerprint IS NULL THEN 'global_file'
        ELSE 'workspace_file'
    END
WHERE asset_key = '';

CREATE INDEX idx_mode_definitions_profile_tab_scope ON mode_definitions(profile_id, top_level_tab, scope, workspace_fingerprint);
CREATE INDEX idx_rulesets_profile_scope ON rulesets(profile_id, scope, workspace_fingerprint);
CREATE INDEX idx_skillfiles_profile_scope ON skillfiles(profile_id, scope, workspace_fingerprint);
`,
    },
    {
        name: '005_registry_precedence_indexes.sql',
        sql: `
DROP INDEX IF EXISTS idx_mode_definitions_profile_tab_mode;
DROP INDEX IF EXISTS idx_rulesets_profile_scope_name;
DROP INDEX IF EXISTS idx_skillfiles_profile_scope_name;

CREATE UNIQUE INDEX idx_mode_definitions_profile_registry_asset
    ON mode_definitions(profile_id, top_level_tab, scope, ifnull(workspace_fingerprint, ''), asset_key);

CREATE UNIQUE INDEX idx_rulesets_profile_registry_asset
    ON rulesets(profile_id, scope, ifnull(workspace_fingerprint, ''), asset_key);

CREATE UNIQUE INDEX idx_skillfiles_profile_registry_asset
    ON skillfiles(profile_id, scope, ifnull(workspace_fingerprint, ''), asset_key);
`,
    },
    {
        name: '006_session_attached_skills.sql',
        sql: `
CREATE TABLE session_attached_skills (
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    asset_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (session_id, asset_key)
);

CREATE INDEX idx_session_attached_skills_profile_session
    ON session_attached_skills(profile_id, session_id, created_at);
`,
    },
    {
        name: '007_run_command_shell_approvals.sql',
        sql: `
ALTER TABLE permissions ADD COLUMN command_text TEXT NULL;
ALTER TABLE permissions ADD COLUMN approval_candidates_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE permissions ADD COLUMN selected_approval_resource TEXT NULL;

UPDATE tools_catalog
SET permission_policy = 'ask'
WHERE id = 'run_command';
`,
    },
];
