name: Build Beta

on:
  push:
    tags:
      - "v*-beta.*"

permissions:
  contents: write
  pull-requests: read

jobs:
  prerelease:
    uses: ./.github/workflows/build-prerelease.yml
    with:
      channel: beta
      channel_title: Beta
      tag_pattern: v*-beta.*
      target_branch: prev
    secrets: inherit
